.\" (C) Copyright 2013 Ravikiran Janardhana <ravikiran.j.127@gmail.com>,
.TH breakmywork
.SH NAME
\fBbreakmywork \fP- a repetitive strain injury (RSI) prevention tool
\fB
.SH SYNOPSIS
.nf
.fam C
\fBbreakmywork\fP

.fam T
.fi
.fam T
.fi
.SH DESCRIPTION
\fBbreakmywork\fP reminds the user to take periodic breaks while working
long hours in front of a computer.
