.\" (C) Copyright 2013 Ravikiran Janardhana <ravikiran.j.127@gmail.com>,
.TH BREAKMYWORK 1 "APRIL 2013" Linux "User Manuals"
.SH NAME
breakmywork - a repetitive strain injury (RSI) prevention tool
\fB
.SH SYNOPSIS
.B breakmywork
.SH DESCRIPTION
breakmywork reminds the user to take periodic breaks while working
long hours in front of a computer.
.SH AUTHOR
Ravikiran Janardhana <ravikiran.j.127 at gmail.com>
.SH "ADDITIONAL INFO"
To run the command in background type 'breakmywork & disown' on the command line.
