Document: breakmywork
Title: Debian breakmywork Manual
Author: <insert document author here>
Abstract: This manual describes what breakmywork is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/breakmywork/breakmywork.sgml.gz

Format: postscript
Files: /usr/share/doc/breakmywork/breakmywork.ps.gz

Format: text
Files: /usr/share/doc/breakmywork/breakmywork.text.gz

Format: HTML
Index: /usr/share/doc/breakmywork/html/index.html
Files: /usr/share/doc/breakmywork/html/*.html
